# <b> Problem Statement </b>


You work as a Business Analytics Consultant at the Bank of Corporate.The bank was witnessing slower than usual growth in its book of business for the most recent quarter in 2018. The bank provides financial services/products such as savings accounts, current accounts, debit cards, etc. to its customer. The data suggested that it was the home loan business of the bank that was hit by a major loss. Now, loans are the core business of banks. The main profit comes directly from the loan’s interest. The head of the Home Loan business asked the heads of the Sales, Operations, Risk and Analytics teams to investigate and identify the root causes for the slowing growth and solve the problem. A business like selling Home Loans can grow or shrink based on several factors like demand or supply side. Some of the reasons are:

- <b> Demand Side: </b> Are interest rates high?
- <b> Demand Side: </b> Are there any macro economic reasons, such as recession or low salary growth or inflation?
- <b> Supply Side: </b> Are new and attractive housing projects not available in the markets being served?
- <b> Supply Side: </b> Have real estate prices shot up making homes unaffordable, relatively speaking?
- <b> Competitor Side: </b> Are we losing customers to our competition? Is our competition also facing lower growth?



The team found out that the credit risk was in abnormal standards and the default loan rates were high. So what do you mean by default loans and credit risk?

<b> Deafult loans : </b> <br>
Default is the failure to repay a loan according to the terms agreed to in the promissory note. For most federal student loans, you will default if you have not made a payment in more than 270 days.

<b> Credit risk : </b> <br>
It is understood simply as the risk a bank takes while lending out money to borrowers. They might default and fail to repay the dues in time and these results in losses to the bank. 

## <b> So, what do banks do then? </b> <br>
They need to manage their credit risks. The goal of credit risk management in banks is to maintain credit risk exposure within proper and acceptable parameters. It is the practice of mitigating losses by understanding the adequacy of a bank’s capital and loan loss reserves at any given time. For this, banks not only need to manage the entire portfolio but also individual credits.

## <b> Measures taken </b> <br>
So in 2019, the bank came up with a project to build a "Credit risk estimate model" for its home loan branch.The loan should be granted after an intensive process of verification and validation. The dataset (provided below) contains the information about all the customers who were contacted during this year and were provided loans based on various parameters. The "Credit risk estimate model" need to be cost-efficient so that the bank not only decreases their credit risk but also increase the total profit.


## <b> Business objective </b> <br>

Your aim is to build the "Credit risk estimate model" to classify new loans availed as "Low Risk", "High Risk" and "Medium Risk". This will help the bank to sanction loans to "Low Risk" customers, following up with the latest information/data for the "Medium Risk" customers and reject the loan approval for "High Risk" customers.

## <b> Read the dataset

In [72]:
#Import the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

#Load the loan dataset
loan_data = pd.read_csv('loan.csv')
#Details of the dataset
loan_data

,id,loan_amnt,funded_amnt,int_rate,installment,emp_length,annual_inc,loan_status
0,1077501,5000,5000,10.65,162.87,10,24000.0,Low Risk
1,1077430,2500,2500,15.27,59.83,1,30000.0,High Risk
2,1077175,2400,2400,15.96,84.33,10,12252.0,Low Risk
3,1076863,10000,10000,13.49,339.31,10,49200.0,Low Risk
4,1075358,3000,3000,12.69,67.79,1,80000.0,Medium Risk
...,...,...,...,...,...,...,...,...
38637,92187,2500,2500,8.07,78.42,4,110000.0,Low Risk
38638,90665,8500,8500,10.28,275.38,3,18000.0,Low Risk
38639,90395,5000,5000,8.07,156.84,1,100000.0,Low Risk
38640,90376,5000,5000,7.43,155.38,1,200000.0,Low Risk
38641,87023,7500,7500,13.75,255.43,1,22000.0,Low Risk

In [73]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38642 entries, 0 to 38641
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           38642 non-null  int64
 1   loan_amnt    38642 non-null  int64
 2   funded_amnt  38642 non-null  int64
 3   int_rate     38642 non-null  float64
 4   installment  38642 non-null  float64
 5   emp_length   38642 non-null  int64
 6   annual_inc   38642 non-null  float64
 7   loan_status  38642 non-null  object
dtypes: float64(3), int64(4), object(1)
memory usage: 2.4+ MB

The dataset has the following columns: </b>

<b> id : </b>Transaction ID use to identify each transaction uniquely <br>
<b> loan_amnt : </b> Loan amount that was requested by the customer <br>
<b> funded_amnt : </b>Amount that was sanctioned by the bank <br>
<b> int_rate : </b> Interest rate offered on the loan amount <br>
<b> installment : </b>Amount of money paid during each installment <br>
<b> emp_length :  </b> Work experience (employment length of the customer)  <br>
<b> annual_inc : </b>What is the annual income of the customer<br>
<b> loan_status : </b> Classified as whether it is "High Risk", "Low Risk" and "Medium Risk" <br>

In [74]:
#Check the details of the dataset
loan_data.head()

,id,loan_amnt,funded_amnt,int_rate,installment,emp_length,annual_inc,loan_status
0,1077501,5000,5000,10.65,162.87,10,24000.0,Low Risk
1,1077430,2500,2500,15.27,59.83,1,30000.0,High Risk
2,1077175,2400,2400,15.96,84.33,10,12252.0,Low Risk
3,1076863,10000,10000,13.49,339.31,10,49200.0,Low Risk
4,1075358,3000,3000,12.69,67.79,1,80000.0,Medium Risk

In [75]:
# Distribution of the target variable
loan_data['loan_status'].value_counts()

loan_status
Low Risk       32145
High Risk       5399
Medium Risk     1098
Name: count, dtype: int64

## <b> Data Cleaning </b>

In [76]:
#Check for null values
loan_data.isnull().sum()

id             0
loan_amnt      0
funded_amnt    0
int_rate       0
installment    0
emp_length     0
annual_inc     0
loan_status    0
dtype: int64

In [77]:
#Check for duplicate values
loan_data.duplicated().sum()

0

## <b> Feature Creation </b>
<b> funded_amnt: </b> Percentage of amount sanctioned compared to the total loan amount. Higher the value, it states that the bank is positive in lending the loan to the customer. <br>
<b> incToloan_perc: </b> Percentage of annual income when compared to the loan amount. Higher the value it states that the customer is more likely to pay back without defaulting.

In [78]:
# Adding new variables  
# fund_perc variable represents the ratio of funded amount wrt loan amount
loan_data['fund_perc'] = loan_data['funded_amnt']/loan_data['loan_amnt']

#incToloan_perc variable represent the ratio of annula income wrt loan amount
loan_data['incToloan_perc'] = loan_data['annual_inc']/loan_data['loan_amnt']

In [79]:
loan_data

,id,loan_amnt,funded_amnt,int_rate,installment,emp_length,annual_inc,loan_status,fund_perc,incToloan_perc
0,1077501,5000,5000,10.65,162.87,10,24000.0,Low Risk,1.0,4.800000
1,1077430,2500,2500,15.27,59.83,1,30000.0,High Risk,1.0,12.000000
2,1077175,2400,2400,15.96,84.33,10,12252.0,Low Risk,1.0,5.105000
3,1076863,10000,10000,13.49,339.31,10,49200.0,Low Risk,1.0,4.920000
4,1075358,3000,3000,12.69,67.79,1,80000.0,Medium Risk,1.0,26.666667
...,...,...,...,...,...,...,...,...,...,...
38637,92187,2500,2500,8.07,78.42,4,110000.0,Low Risk,1.0,44.000000
38638,90665,8500,8500,10.28,275.38,3,18000.0,Low Risk,1.0,2.117647
38639,90395,5000,5000,8.07,156.84,1,100000.0,Low Risk,1.0,20.000000
38640,90376,5000,5000,7.43,155.38,1,200000.0,Low Risk,1.0,40.000000
38641,87023,7500,7500,13.75,255.43,1,22000.0,Low Risk,1.0,2.933333

In [80]:
# Understanding distribution of all the numerical variables in dataset
loan_data.describe()

,id,loan_amnt,funded_amnt,int_rate,installment,emp_length,annual_inc,fund_perc,incToloan_perc
count,3.864200e+04,38642.000000,38642.000000,38642.000000,38642.000000,38642.000000,3.864200e+04,38642.000000,38642.000000
mean,6.810404e+05,11291.615988,11017.101211,12.052427,326.760477,5.092050,6.960828e+04,0.985571,8.915950
std,2.113045e+05,7462.136215,7193.038828,3.716705,209.143908,3.408338,6.425320e+04,0.070317,13.845454
min,5.473400e+04,500.000000,500.000000,5.420000,15.690000,1.000000,4.000000e+03,0.101250,1.204819
25%,5.134350e+05,5500.000000,5500.000000,9.320000,168.442500,2.000000,4.140000e+04,1.000000,4.000000
50%,6.627705e+05,10000.000000,9950.000000,11.860000,282.830000,4.000000,6.000000e+04,1.000000,6.066667
75%,8.364912e+05,15000.000000,15000.000000,14.590000,434.397500,9.000000,8.319999e+04,1.000000,10.016699
max,1.077501e+06,35000.000000,35000.000000,24.590000,1305.190000,10.000000,6.000000e+06,1.000000,1266.666667

In [81]:
#column names
loan_data.columns

Index(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'emp_length', 'annual_inc', 'loan_status', 'fund_perc',
       'incToloan_perc'],
      dtype='object')

## <b> Train-Test Split

In [82]:
# choosing all the numerical variables as independent variables (classifier can only take numerical input)
# dropping two variable funded_amnt as we have created new variable transformation based on it 
X = loan_data.select_dtypes(np.number).drop(['id','funded_amnt'], axis=1)

#Dependent variable representing status of the loan
y = loan_data['loan_status']

#splitting the dataset in train and test datasets using a split ratio of 70:30
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

# standardizing all the variables using standard scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## <b> Model Building

In [83]:
from sklearn.linear_model import LogisticRegression 
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import warnings

In [84]:

# Building a classification model using one vs rest method
LR = LogisticRegression()
oneVsrest = OneVsRestClassifier(LR)

# Fitting the model with training data
oneVsrest.fit(X_train_scaled, y_train)

OneVsRestClassifier(estimator=LogisticRegression())

## <b>Step 3 : </b>
<b> Model Prediction </b>

In [85]:
# Making a prediction on the test set
prediction_oneVsrest = oneVsrest.predict(X_test_scaled)
   
# Evaluating the model
print(f"Test set accuracy : {accuracy_score(y_test, prediction_oneVsrest)*100} %\n\n")
print(f"Classification Report :\n\n {classification_report(y_test,prediction_oneVsrest)}")

Test set accuracy : 82.88622444578625 %


Classification Report :

               precision    recall  f1-score   support

   High Risk       0.56      0.01      0.01      1654
    Low Risk       0.83      1.00      0.91      9607
 Medium Risk       0.20      0.00      0.01       332

    accuracy                           0.83     11593
   macro avg       0.53      0.34      0.31     11593
weighted avg       0.77      0.83      0.75     11593

<b> Accuracy : </b> Accuracy is the most intuitive performance measure and it is simply a ratio of correctly predicted observation to the total observations.The formula is given as: <br>
<b> *Accuracy = True Positives + True Negatives/True Positives+False Positives+False Negatives+True Positives* </b> <br> <br>
<b> Precision : </b> The quality of being exact and refers to how close two or more measurements are to each other, regardless of whether those measurements are accurate or not. The formula is : <br>
<b> *Precision = True Positives / (True Positives + False Positives)* </b> <br> <br>
<b> Recall : </b> It is calculated as the number of true positives divided by the total number of true positives and false negatives. The result is a value between 0.0 for no recall and 1.0 for full or perfect recall. The formula is : <br>
<b> *Recall = True Positives / (True Positives + False Negatives)* </b> <br> <br>
<b> F1 score : </b> F1 Score is the weighted average of Precision and Recall. Therefore, this score takes both false positives and false negatives into account.The highest possible value of an F-score is 1.0, indicating perfect precision and recall, and the lowest possible value is 0, if either the precision or the recall is zero. The formula is : <br>
<b> *F1 score = 2\*((precision\*recall)/(precision+recall))* </b> <br> <br>

## <b>Analysing the probabilties and classification values </b>

In [91]:
# Adding followig variables to the test dataset

#Scaled feature array
X_test['Scaled_features'] = X_test_scaled.tolist()

#Actual target variable
X_test['Actual'] = y_test

#OnevsRest target prediction
X_test['prediction_oneVsrest'] = prediction_oneVsrest

#OnevsRest probability prediction
X_test['prob_pred_oneVsrest'] = oneVsrest.predict_proba(X_test_scaled).tolist()

#OnevsRest individual class prediction probabilities
X_test['prob_pred_oneVsrest_highRisk'] = oneVsrest.predict_proba(X_test_scaled)[:,0].tolist()
X_test['prob_pred_oneVsrest_lowRisk'] = oneVsrest.predict_proba(X_test_scaled)[:,1].tolist()
X_test['prob_pred_oneVsrest_mediumRisk'] = oneVsrest.predict_proba(X_test_scaled)[:,2].tolist()

X_test.head()

,loan_amnt,int_rate,installment,emp_length,annual_inc,fund_perc,incToloan_perc,Scaled_features,Actual,prediction_oneVsrest,prob_pred_oneVsrest,prob_pred_oneVsrest_highRisk,prob_pred_oneVsrest_lowRisk,prob_pred_oneVsrest_mediumRisk
17614,25000,16.77,888.46,1,104000.0,1.0,4.160000,"[1.8371293187309605, 1.2736784709856193, 2.678...",Low Risk,Low Risk,"[0.13525218042334342, 0.8646560093263703, 9.18...",0.135252,0.864656,0.000092
3728,3600,7.51,112.00,2,31800.0,1.0,8.833333,"[-1.0230547720561989, -1.2180942746831072, -1....",Low Risk,Low Risk,"[0.07646369886774125, 0.9198189437044249, 0.00...",0.076464,0.919819,0.003717
37880,9000,11.97,298.80,2,57500.0,1.0,6.388889,"[-0.30132607625009317, -0.017953189836182465, ...",Low Risk,Low Risk,"[0.11704339245013136, 0.8793929925447623, 0.00...",0.117043,0.879393,0.003564
33951,17000,12.18,566.10,10,63504.0,1.0,3.735529,"[0.7679016212404337, 0.03855569532477113, 1.14...",High Risk,Low Risk,"[0.12153136815366948, 0.877470777257808, 0.000...",0.121531,0.877471,0.000998
982,5500,14.27,188.70,5,24000.0,1.0,4.363636,"[-0.7691131939021987, 0.6009536476409307, -0.6...",Low Risk,Low Risk,"[0.19505971797192978, 0.7912622431036758, 0.01...",0.195060,0.791262,0.013678

## <b>Display the coefficient and intercept values for each Logistic Regression model </b>

In [92]:
# Classes for which individual models are created
print(oneVsrest.classes_)

#Coefficient matrix for all the models created
print(oneVsrest.coef_.shape)

#Intercept values for all the models created
print('\n Intercept Values')
print(oneVsrest.intercept_)

#Coefficient values for all the models created
print("\n Coefficient Values")
Coeff_array = oneVsrest.coef_
print(Coeff_array)

['High Risk' 'Low Risk' 'Medium Risk']

AttributeError: 'OneVsRestClassifier' object has no attribute 'coef_'

## <b>Analyse probability values for one test sample</b>

In [93]:
print(X_test.iloc[0]['prob_pred_oneVsrest'])

[0.13525218042334342, 0.8646560093263703, 9.181025028618748e-05]

## <b>Understand the mathematics and calculations inside the Model </b>

In [96]:
#Below example demonstrate the calculation of prediction probability for a observation in the dataset
#The demonstartion uses coefficient values of each model for the calculation

# Choose the first observation
arr = X_test.iloc[0]['Scaled_features']

# Class calculates the log of odds value for a given class
def y(class_cat,input_arr):
    val = 0
    for i in range(7):
        val += Coeff_array[class_cat - 1][i]*input_arr[i]
        
    return val

# Calculates the probability values given the log of odds
def z(a):
    return(1/(1+np.exp(-a)))

#Non-normalized probability of all the classes
z_non_norm = z(sum(oneVsrest.intercept_[0],y(1,arr))),z(sum(oneVsrest.intercept_[1],y(2,arr))),z(sum(oneVsrest.intercept_[2],y(3,arr)))

#Normalized probability of all the classes
z_norm = z_non_norm/sum(z_non_norm)

print(z_non_norm)
print(z_norm)

AttributeError: 'OneVsRestClassifier' object has no attribute 'intercept_'

## <b> Building Logistic Regression Model and using it in One vs One Classifier </b>

In [98]:
#Classification using OnevsOne method
LR1 = LogisticRegression()
OnevsOne = OneVsOneClassifier(LR1)

# Fitting the model with training data
OnevsOne.fit(X_train_scaled, y_train)
   
# Making a prediction on the test set
prediction_OnevsOne = OnevsOne.predict(X_test_scaled)

## <b> Model Prediction </b>

In [99]:
# Evaluating the model
print(f"Test set accuracy {accuracy_score(y_test,prediction_OnevsOne)*100} %\n\n")
print(f"classification accuracy report : \n\n {classification_report(y_test,prediction_OnevsOne)}")

Test set accuracy 82.85172086603984 %


classification accuracy report :

               precision    recall  f1-score   support

   High Risk       0.75      0.00      0.01      1654
    Low Risk       0.83      1.00      0.91      9607
 Medium Risk       0.14      0.01      0.01       332

    accuracy                           0.83     11593
   macro avg       0.57      0.34      0.31     11593
weighted avg       0.80      0.83      0.75     11593

## <b>Analysing the probabilties and classification values </b>

In [101]:
# Adding followig variables to the test dataset
X_test['prediction_oneVsone'] = prediction_OnevsOne

#OnevsOne target prediction
X_test.head()

,loan_amnt,int_rate,installment,emp_length,annual_inc,fund_perc,incToloan_perc,Scaled_features,Actual,prediction_oneVsrest,prob_pred_oneVsrest,prob_pred_oneVsrest_highRisk,prob_pred_oneVsrest_lowRisk,prob_pred_oneVsrest_mediumRisk,prediction_oneVsone
17614,25000,16.77,888.46,1,104000.0,1.0,4.160000,"[1.8371293187309605, 1.2736784709856193, 2.678...",Low Risk,Low Risk,"[0.13525218042334342, 0.8646560093263703, 9.18...",0.135252,0.864656,0.000092,Low Risk
3728,3600,7.51,112.00,2,31800.0,1.0,8.833333,"[-1.0230547720561989, -1.2180942746831072, -1....",Low Risk,Low Risk,"[0.07646369886774125, 0.9198189437044249, 0.00...",0.076464,0.919819,0.003717,Low Risk
37880,9000,11.97,298.80,2,57500.0,1.0,6.388889,"[-0.30132607625009317, -0.017953189836182465, ...",Low Risk,Low Risk,"[0.11704339245013136, 0.8793929925447623, 0.00...",0.117043,0.879393,0.003564,Low Risk
33951,17000,12.18,566.10,10,63504.0,1.0,3.735529,"[0.7679016212404337, 0.03855569532477113, 1.14...",High Risk,Low Risk,"[0.12153136815366948, 0.877470777257808, 0.000...",0.121531,0.877471,0.000998,Low Risk
982,5500,14.27,188.70,5,24000.0,1.0,4.363636,"[-0.7691131939021987, 0.6009536476409307, -0.6...",Low Risk,Low Risk,"[0.19505971797192978, 0.7912622431036758, 0.01...",0.195060,0.791262,0.013678,Low Risk

## <b>Display the parameters and coefficients for each Logistic Regression model </b>

In [105]:
#OneVsOne.classes_

OnevsOne.classes_

array(['High Risk', 'Low Risk', 'Medium Risk'], dtype=object)